-- Tema: Cursores

CREATE TABLE G8_CATEGORIA(
    COD_CAT INTEGER,
    NOMBRE_CAT VARCHAR(50) NOT NULL,
    PRIMARY KEY(COD_CAT)
);

CREATE TABLE G8_CLIENTE(
    RUT_CLI VARCHAR(11),
    NOMBRE_CLI VARCHAR(50) NOT NULL,
    PRIMARY KEY(RUT_CLI)
);

CREATE TABLE G8_TEMPORADA(
    COD_TEMP INTEGER,
    NOMBRE_TEMP VARCHAR(50) NOT NULL,
    MES_INICIO DATE NOT NULL,
    MES_FIN DATE,
    PRIMARY KEY(COD_TEMP)
);

CREATE TABLE G8_PRODUCTO(
    COD_PR INTEGER,
    NOMBRE_PR VARCHAR(50) NOT NULL,
    PRECIO_COMPRA INTEGER,
    PRECIO_VENTA INTEGER,
    STOCK INTEGER,
    COD_CAT_FK INTEGER,
    PRIMARY KEY(COD_PR),
    FOREIGN KEY(COD_CAT_FK) REFERENCES G8_CATEGORIA(COD_CAT)
);

CREATE TABLE G8_PROD_TEMP(
    COD_PR_FK INTEGER,
    COD_TEMP_FK INTEGER,
    PRIMARY KEY(COD_PR_FK, COD_TEMP_FK),
    FOREIGN KEY(COD_PR_FK) REFERENCES G8_PRODUCTO(COD_PR),
    FOREIGN KEY(COD_TEMP_FK) REFERENCES G8_TEMPORADA(COD_TEMP)
);

CREATE TABLE G8_VENTA(
    COD_PR_FK INTEGER,
    RUT_CLI_FK VARCHAR(11),
    FECHA DATE,
    VALOR_FINAL INTEGER,
    VALOR_DESCUENTO INTEGER,
    PRIMARY KEY(COD_PR_FK,RUT_CLI_FK, FECHA),
    FOREIGN KEY(COD_PR_FK) REFERENCES G8_PRODUCTO(COD_PR),
    FOREIGN KEY(RUT_CLI_FK) REFERENCES G8_CLIENTE(RUT_CLI)
);