-- CREACION DE TABLA
CREATE TABLE PERSONA (
    ID number, 
    NOMBRE varchar2(10), 
    SUELDO number(8),
    GENERO VARCHAR2(1)
);
-- INSERCIÓN ALEATORIA DE DATOS PARA PRUEBA
BEGIN
    FOR I IN 1..100000
    LOOP
        INSERT INTO PERSONA VALUES 
        (I,DBMS_RANDOM.STRING('U',10),DBMS_RANDOM.VALUE(200000,1000000),
        CASE WHEN ROUND(DBMS_RANDOM.VALUE(0,1))=1 THEN 'F' ELSE 'M' END);
        IF MOD(I, 10000) = 0 then
            COMMIT;
        END IF;
    END LOOP;
END;

-- CONOCER LOS INDICES
SELECT * FROM ALL_INDEXES WHERE TABLE_NAME='PERSONA';

SELECT ID FROM PERSONA WHERE ID> 50000

-- AGREGAR INDICE IMPLICITO
ALTER TABLE PERSONA ADD CONSTRAINT PK_ID PRIMARY KEY(ID);

-- CONSULTAR SOLO INDICES DEL USUARIO CONECTADO
SELECT * FROM USER_INDEXES

SELECT NOMBRE FROM PERSONA WHERE NOMBRE LIKE 'L%'

-- CREACIÓN DE ÍNDICE ÚNICO
CREATE UNIQUE INDEX IN_NOMBRE ON PERSONA(NOMBRE);

-- MONITOREAR USO DE ÍNDICES
ALTER INDEX IN_NOMBRE MONITORING USAGE;
SELECT * FROM USER_OBJECT_USAGE;
ALTER INDEX IN_NOMBRE NOMONITORING USAGE;
-- CREAR INDÍCE CON DATOS REPETITIVOS

SELECT NOMBRE, GENERO FROM PERSONA WHERE NOMBRE LIKE 'L%' AND GENERO='F'
CREATE BITMAP INDEX IN_GENERO ON PERSONA(GENERO);

-- CREAR ÍNDICES REGULARES
SELECT NOMBRE, SUELDO FROM PERSONA WHERE SUELDO BETWEEN 500000 AND 700000
CREATE INDEX IN_SUELDO ON PERSONA(SUELDO) -- ESTE INDÍCE NO CONVIENE MANTENERLO
-- BORRAR ÍNDICES 

DROP INDEX IN_SUELDO;

